name: CI

on: 
  push:
    branches:    
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, build and test
      run: |
        npm install
        npm run build
        npm run test
      env:
        CI: true
  danger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      if: github.event_name  == 'pull_request'
    - uses: actions/setup-node@v1
      if: github.event_name  == 'pull_request'
      with:
        node-version: 12.x
    - uses: actions/setup-ruby@v1
      if: github.event_name  == 'pull_request'
      with:
        ruby-version: '2.6'
    - name: npm install
      if: github.event_name  == 'pull_request'
      run: |
        npm install
      env:
        CI: true
    - uses: MeilCli/danger-action@v1
      if: github.event_name  == 'pull_request'
      with:
        plugins_file: 'Gemfile'
        danger_file: 'Dangerfile'
        danger_id: 'danger-pr'
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
