name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm run build
      - run: npm run test
      - run: npm run pack
        if: github.event_name != 'pull_request'
      - name: Create Pull Request
        if: github.event_name != 'pull_request'
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.MEILCLI_BOT }}
          commit-message: 'update actions'
          title: 'update actions'
          labels: 'Action'
          assignees: 'MeilCli'
          reviewers: 'MeilCli'
          branch: 'update/action'
  danger:
    runs-on: ubuntu-latest
    if: github.event_name  == 'pull_request'
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: npm install
        run: |
          npm install
        env:
          CI: true
      - uses: MeilCli/danger-action@v5
        with:
          plugins_file: 'Gemfile'
          danger_file: 'Dangerfile'
          danger_id: 'danger-pr'
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
